---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: arch
    driver_config:
      image: 'logankoester/archlinux-chef'
      platform: arch
      disable_upstart: true
      require_chef_omnibus: false
      provision_command:
        - pacman -S --noconfirm --needed supervisor
      run_command: '/usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes && /usr/sbin/supervisord -c /etc/supervisord.conf -n'

suites:
  - name: default
    driver_config:
      hostname: default
    run_list:
      - 'recipe[supervisor]'
      - 'recipe[website]'
    attributes:
      nginx:
        supervisor: true
      sites:
        'default.example':
          language: 'php'
          ssl:
            common_name: 'default.example'
