source 'https://rubygems.org'

gem 'berkshelf'
gem 'rspec'
gem 'chefspec'
gem 'rubocop'
gem 'foodcritic'
gem 'test-kitchen'
gem 'kitchen-docker', github: 'portertech/kitchen-docker', branch: 'master'
gem 'serverspec'

gem 'guard'
gem 'guard-rspec'
gem 'guard-kitchen', github: 'test-kitchen/guard-kitchen', branch: 'master'
gem 'guard-foodcritic'
